---
title: "My Fire Mixtape"
author: "Eric, Yingtong, Jatin"
date: "3/6/2021"
output: html_document
---

```{r message=FALSE}
library(bayesplot)
library(rstanarm)
library(rstan)
library(bayesrules)
library(tidyverse)
library(janitor)
```

```{r Load Data}
music <- read.csv("music.csv", header=TRUE, stringsAsFactors=FALSE)
```

## Data Cleaning

We remove features that have at least half of their data missing or are non-informative.


```{r Data Cleaning}
# This one removes all the super unnecessary features
keep <- c("artist.familiarity","artist.hotttnesss",	"artist.name",
          "artist.terms",	"song.bars_confidence",	"song.bars_start",
          "song.beats_confidence",	"song.beats_start",
          "song.duration", "song.end_of_fade_in",	"song.hotttnesss",
          "song.key", "song.key_confidence",	"song.loudness",
          "song.mode", "song.mode_confidence", 
          "song.start_of_fade_out", "song.tatums_confidence",
          "song.tatums_start", "song.tempo", "song.time_signature", 
          "song.time_signature_confidence",	"song.year"
) 
# This one is just the variables we are going to use for our analysis
# I just choose a subsection so it's easier to see
keep2 <- c("song.hotttnesss", "artist.familiarity", "artist.name", 
           "artist.hotttnesss", "artist.terms", "song.loudness", 
           "song.tempo", "song.duration", "song.key", "song.time_signature")
smallMusic <- music[keep]
smallMusic2 <- music[keep2]
```


```{r Remove Missing Data}
# This dataset writes it's missing values as -1 and 0 which is really confusing.
# If we are predicting on a song's hotness, we remove all the rows where we don't know the outcome.
# We have a remaining 4000 rows. We lost about 60% of the data.
smallMusic2 <- subset(smallMusic2, song.hotttnesss > 0)
smallMusic <- subset(smallMusic, song.hotttnesss > 0)

```

# Initial Visualizations
```{r Summary}
summary(smallMusic2)
#table(smallMusic2$artist.terms)

ggplot(smallMusic2, aes(x = artist.familiarity, y = song.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")

ggplot(smallMusic2, aes(x = artist.hotttnesss, y = song.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")

ggplot(smallMusic2, aes(x = artist.familiarity, y=artist.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")

ggplot(smallMusic2, aes(x = song.loudness, y=song.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")

ggplot(smallMusic2, aes(x = song.duration, y=song.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")

ggplot(smallMusic2, aes(x = song.tempo, y=song.hotttnesss)) +
  geom_point(size = 0.2) +
  geom_smooth(method = "lm")
```

# Prior Model

```{r}
# Beta_0
plot_normal(0.15, 0.1) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title = 'beta_0')

# Beta_1 
plot_normal(0.5, 0.18) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title = 'beta_1')

# Beta_2
plot_normal(0.4, 0.2) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title = 'beta_2')

# Beta_3
plot_normal(0.22, 0.1) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title = 'beta_3')
```



# Model Fitting
```{r}
#don't work: song.duration, song.tempo, song.loudness, song.time_signature, song.ke

model_g <- stan_glm(song.hotttnesss ~ artist.familiarity + artist.hotttnesss + artist.familiarity:artist.hotttnesss,
          family = gaussian, data = smallMusic,
          chains = 4, iter = 5000*2, seed = 84735, refresh = FALSE)
```

# Model Summary
```{r}
summary(model_g)

prior_summary(model_g)
```

# Model Fit Visualization
```{r}
mcmc_trace(model_g)
mcmc_dens_overlay(model_g)
pp_check(model_g)
```


# Credible Intervals
```{r}
posterior_interval(model_g, prob = 0.80)
```


# Posterior Prediction
```{r}
set.seed(84735)

beyonce <- c(0.89, 0.61) # This is researched information (2010)
predict_beyonce <- posterior_predict(model_g, newdata = data.frame(artist.familiarity = beyonce[1], 
                                                                   artist.hotttnesss = beyonce[2]))
mcmc_dens(predict_beyonce) +
  xlab("Beyoncé's Song Hotttnesss")

amber_nicholson <- c(0.30328380, 0)
predict_amber <- posterior_predict(model_g, newdata = data.frame(artist.familiarity = amber_nicholson[1], artist.hotttnesss = amber_nicholson[2]))
mcmc_dens(predict_amber) +
  xlab("Amber Nicholson's Song Hotttnesss")

bill_boyd_cowboy_ramblers <- c(0, 0)
predict_bill <- posterior_predict(model_g, newdata = data.frame(artist.familiarity = bill_boyd_cowboy_ramblers[1], artist.hotttnesss = bill_boyd_cowboy_ramblers[2]))
mcmc_dens(predict_bill) +
  xlab("Billy Boyd Cowboy Ramblers' Song Hotttnesss")
```

```{r}
predictions <- data.frame(y_new = predict_beyonce[,1]) 
predictions %>% 
  summarize(lower_80 = quantile(y_new, 0.1),
    upper_80 = quantile(y_new, 0.9))

predictions <- data.frame(y_new = predict_amber[,1]) 
predictions %>% 
  summarize(lower_80 = quantile(y_new, 0.1),
    upper_80 = quantile(y_new, 0.9))

predictions <- data.frame(y_new = predict_bill[,1]) 
predictions %>% 
  summarize(lower_80 = quantile(y_new, 0.1),
    upper_80 = quantile(y_new, 0.9))
```

